# Generated by Django 6.0.2 on 2026-02-27 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('repo', 'Repository'), ('website', 'Website')], max_length=20)),
                ('ai_target', models.CharField(choices=[('gpt', 'GPT'), ('claude', 'Claude'), ('midjourney', 'Midjourney')], max_length=20)),
                ('mode', models.CharField(choices=[('standard', 'Standard'), ('api', 'API')], max_length=20)),
                ('character_limit', models.IntegerField(default=1500)),
                ('raw_input', models.TextField()),
                ('generated_prompt', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
